---
- hosts: all
  become: true
  tasks:

    - name: install updates (Rocky)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: install update (Debian-Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"


- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php for Debian and Ubuntu servers
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_facts['os_family'] == "Debian"

    - name: install apache and php packages for Rocky server
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
